### ISSUE TITLE
batch_size > 1

### ISSUE THREAD

**Issue by UcanYusuf** [thaitc-hust/yolov9-tensorrt#7]
Hello, how can I increase batch size? As I understand default batch_size=1.

**Comment by frk-tt** [comment]
@UcanYusuf  in https://github.com/thaitc-hust/yolov9-tensorrt/blob/0d8ce42e9e85bcdd8ca0fc090a90ff558ff3f28a/object_detector_trt_nms.py#L294C9-L294C12
```inp``` is batch image, you can append other image to it
